-- =========================================================
-- PERSONAL MONTHLY BUDGET PLANNER
-- Supabase database setup
-- =========================================================


-- =========================================================
-- 1. PROFILES
-- Stores the user's profile-card information
-- =========================================================

create table if not exists public.profiles (
    user_id uuid primary key
        references auth.users(id)
        on delete cascade,

    full_name text not null default '',
    designation text not null default '',
    company text not null default '',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- =========================================================
-- 2. CATEGORIES
-- user_id = null means it is a predefined category
-- user_id contains a UUID when it is a custom category
-- =========================================================

create table if not exists public.categories (
    id bigint generated by default as identity primary key,

    user_id uuid
        references auth.users(id)
        on delete cascade,

    name text not null,
    created_at timestamptz not null default now(),

    constraint category_name_not_empty
        check (length(trim(name)) > 0)
);


-- Prevent duplicate predefined categories
create unique index if not exists unique_default_category_name
on public.categories (lower(name))
where user_id is null;


-- Prevent a user from creating duplicate custom categories
create unique index if not exists unique_user_category_name
on public.categories (user_id, lower(name))
where user_id is not null;


-- =========================================================
-- 3. MONTHLY INCOMES
-- One income value per user per month
-- The month must always be the first day of the month
-- Example: 2026-07-01
-- =========================================================

create table if not exists public.monthly_incomes (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    month date not null,
    amount numeric(12,2) not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint monthly_income_amount_valid
        check (amount >= 0),

    constraint month_must_be_first_day
        check (month = date_trunc('month', month)::date),

    constraint one_income_per_user_per_month
        unique (user_id, month)
);


-- =========================================================
-- 4. EXPENSES
-- Stores each expense with date and time
-- =========================================================

create table if not exists public.expenses (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    category_id bigint not null
        references public.categories(id)
        on delete restrict,

    amount numeric(12,2) not null,
    expense_datetime timestamptz not null default now(),

    description text,
    is_recurring boolean not null default false,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint expense_amount_must_be_positive
        check (amount > 0),

    constraint description_length_limit
        check (
            description is null
            or length(description) <= 500
        )
);


-- Useful indexes for monthly reports and comparisons
create index if not exists expenses_user_datetime_index
on public.expenses (user_id, expense_datetime desc);

create index if not exists expenses_category_index
on public.expenses (category_id);

create index if not exists monthly_income_user_month_index
on public.monthly_incomes (user_id, month);


-- =========================================================
-- 5. DEFAULT CATEGORIES
-- =========================================================

insert into public.categories (name)
values
    ('Food'),
    ('Clothes'),
    ('Family'),
    ('Bills'),
    ('Subscriptions'),
    ('Pets'),
    ('Friends'),
    ('Other')
on conflict do nothing;


-- =========================================================
-- 6. AUTOMATIC updated_at FUNCTION
-- =========================================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


drop trigger if exists update_profiles_updated_at
on public.profiles;

create trigger update_profiles_updated_at
before update on public.profiles
for each row
execute function public.update_updated_at_column();


drop trigger if exists update_monthly_incomes_updated_at
on public.monthly_incomes;

create trigger update_monthly_incomes_updated_at
before update on public.monthly_incomes
for each row
execute function public.update_updated_at_column();


drop trigger if exists update_expenses_updated_at
on public.expenses;

create trigger update_expenses_updated_at
before update on public.expenses
for each row
execute function public.update_updated_at_column();


-- =========================================================
-- 7. CREATE PROFILE AUTOMATICALLY AFTER SIGN-UP
-- =========================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles (
        user_id,
        full_name,
        designation,
        company
    )
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.raw_user_meta_data ->> 'designation', ''),
        coalesce(new.raw_user_meta_data ->> 'company', '')
    );

    return new;
end;
$$;


drop trigger if exists on_auth_user_created
on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();


-- =========================================================
-- 8. ENABLE ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.monthly_incomes enable row level security;
alter table public.expenses enable row level security;


-- =========================================================
-- 9. PROFILE SECURITY POLICIES
-- =========================================================

drop policy if exists "Users can view their own profile"
on public.profiles;

create policy "Users can view their own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = user_id);


drop policy if exists "Users can update their own profile"
on public.profiles;

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);


-- =========================================================
-- 10. CATEGORY SECURITY POLICIES
-- =========================================================

drop policy if exists "Users can view default and own categories"
on public.categories;

create policy "Users can view default and own categories"
on public.categories
for select
to authenticated
using (
    user_id is null
    or (select auth.uid()) = user_id
);


drop policy if exists "Users can create their own categories"
on public.categories;

create policy "Users can create their own categories"
on public.categories
for insert
to authenticated
with check ((select auth.uid()) = user_id);


drop policy if exists "Users can update their own categories"
on public.categories;

create policy "Users can update their own categories"
on public.categories
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);


drop policy if exists "Users can delete their own categories"
on public.categories;

create policy "Users can delete their own categories"
on public.categories
for delete
to authenticated
using ((select auth.uid()) = user_id);


-- =========================================================
-- 11. MONTHLY-INCOME SECURITY POLICIES
-- =========================================================

drop policy if exists "Users can view their own monthly income"
on public.monthly_incomes;

create policy "Users can view their own monthly income"
on public.monthly_incomes
for select
to authenticated
using ((select auth.uid()) = user_id);


drop policy if exists "Users can create their own monthly income"
on public.monthly_incomes;

create policy "Users can create their own monthly income"
on public.monthly_incomes
for insert
to authenticated
with check ((select auth.uid()) = user_id);


drop policy if exists "Users can update their own monthly income"
on public.monthly_incomes;

create policy "Users can update their own monthly income"
on public.monthly_incomes
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);


drop policy if exists "Users can delete their own monthly income"
on public.monthly_incomes;

create policy "Users can delete their own monthly income"
on public.monthly_incomes
for delete
to authenticated
using ((select auth.uid()) = user_id);


-- =========================================================
-- 12. EXPENSE SECURITY POLICIES
-- =========================================================

drop policy if exists "Users can view their own expenses"
on public.expenses;

create policy "Users can view their own expenses"
on public.expenses
for select
to authenticated
using ((select auth.uid()) = user_id);


drop policy if exists "Users can create their own expenses"
on public.expenses;

create policy "Users can create their own expenses"
on public.expenses
for insert
to authenticated
with check (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.categories
        where categories.id = expenses.category_id
          and (
              categories.user_id is null
              or categories.user_id = (select auth.uid())
          )
    )
);


drop policy if exists "Users can update their own expenses"
on public.expenses;

create policy "Users can update their own expenses"
on public.expenses
for update
to authenticated
using ((select auth.uid()) = user_id)
with check (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.categories
        where categories.id = expenses.category_id
          and (
              categories.user_id is null
              or categories.user_id = (select auth.uid())
          )
    )
);


drop policy if exists "Users can delete their own expenses"
on public.expenses;

create policy "Users can delete their own expenses"
on public.expenses
for delete
to authenticated
using ((select auth.uid()) = user_id);